# Generated by Django 4.2.7 on 2024-01-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderStatus',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
