# Generated by Django 4.2.7 on 2023-12-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='EmployeeAccess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
