# Generated by Django 4.2.7 on 2023-12-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_employeeaccess_user_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table="'main.user'",
        ),
    ]
