# Generated by Django 4.2.7 on 2023-12-17 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublicId', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('TableNumber', models.IntegerField(unique=True)),
                ('TableSits', models.IntegerField(default=2)),
                ('TableFee', models.FloatField(default=0.0)),
                ('TableStatus', models.BooleanField(default=False)),
            ],
            options={
                'db_table': "'main.tables'",
            },
        ),
    ]
