# Generated by Django 4.2.7 on 2024-01-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_table_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='Customer',
        ),
    ]
