# Generated by Django 4.2.7 on 2024-01-08 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('foodorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
        ),
    ]
