# Generated by Django 4.2.7 on 2023-12-29 17:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0002_table_funcstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublicId', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('CustomerName', models.CharField(max_length=100)),
                ('CustomerStatus', models.BooleanField(default=True)),
                ('TableId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.table')),
            ],
            options={
                'db_table': "'main.customer'",
            },
        ),
    ]
